# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release Please
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/create-github-app-token@v2.1.1"
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: "actions/checkout@v5.0.0"
      - uses: "googleapis/release-please-action@v4.3.0"
        with:
          release-type: go
          token: ${{ steps.app-token.outputs.token }}
